(() => {
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const KEY='openshelf_apps'; const SESSION='openshelf_admin_session';
const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)&&x.length?x:APPS.map(a=>structuredClone?structuredClone(a):JSON.parse(JSON.stringify(a)))}catch{return APPS}};
const save=a=>localStorage.setItem(KEY,JSON.stringify(a));
const formIds=['fEditId','fName','fId','fCat','fTag','fDesc','fVersion','fSize','fPlatform','fType','fLink','fDownload','fInitial','fColor','fFeatured'];
let editing=null;
function versionsOf(a){return (a.versions||[]).map(v=>typeof v==='string'?{version:v,url:a.link||a.download||'',label:'Previous release'}:v)}
function renderVersions(rows){$('#versionRows').innerHTML=''; (rows||[]).forEach((v,i)=>addVersionRow(v,i));}
function addVersionRow(v={version:'',url:'',label:'Previous release'},i=null){const row=document.createElement('div');row.className='version-edit-row';row.innerHTML=`<input class="v-version" placeholder="Version" value="${esc(v.version)}"><input class="v-url" type="url" placeholder="Download URL" value="${esc(v.url)}"><input class="v-label" placeholder="Label" value="${esc(v.label||'Previous release')}"><button type="button" class="mini-delete">×</button>`;row.querySelector('.mini-delete').onclick=()=>row.remove();$('#versionRows').appendChild(row)}
function collectVersions(){return [...document.querySelectorAll('.version-edit-row')].map(r=>({version:r.querySelector('.v-version').value.trim(),url:r.querySelector('.v-url').value.trim(),label:r.querySelector('.v-label').value.trim()||'Previous release'})).filter(x=>x.version)}
function resetForm(){editing=null;$('#appForm').reset();$('#fColor').value='#315efb';$('#fType').value='official';$('#editorTitle').textContent='Add new app';$('#saveBtn').textContent='Publish app →';$('#deleteBtn').disabled=true;$('#versionRows').innerHTML='';}
function edit(a){editing=a.id; $('#fEditId').value=a.id; $('#fName').value=a.name||'';$('#fId').value=a.id||'';$('#fCat').value=a.cat||'utility';$('#fTag').value=a.tag||'';$('#fDesc').value=a.desc||'';$('#fVersion').value=a.version||'';$('#fSize').value=a.size||'';$('#fPlatform').value=a.platform||'';$('#fType').value=a.type||'official';$('#fLink').value=a.link||'';$('#fDownload').value=a.download||'';$('#fInitial').value=a.initial||'';$('#fColor').value=a.color||'#315efb';$('#fFeatured').checked=!!a.featured;renderVersions(versionsOf(a));$('#editorTitle').textContent='Edit '+a.name;$('#saveBtn').textContent='Save changes →';$('#deleteBtn').disabled=false;window.scrollTo({top:0,behavior:'smooth'})}
function render(){const a=load(), q=($('#adminSearch')?.value||'').toLowerCase(); const list=a.filter(x=>[x.name,x.id,x.cat,x.tag].join(' ').toLowerCase().includes(q));
$('#adminCount').textContent=`${list.length} of ${a.length} listings`; $('#statApps').textContent=a.length;$('#statFeatured').textContent=a.filter(x=>x.featured).length;$('#statCats').textContent=new Set(a.map(x=>x.cat).filter(Boolean)).size;$('#statVersions').textContent=a.reduce((n,x)=>n+(x.versions?.length||0),0);
$('#adminList').innerHTML=list.length?list.map(x=>`<div class="admin-item"><div class="admin-app-main"><div class="app-icon admin-mini" style="background:${esc(x.color||'#334155')}">${esc(x.initial||x.name?.[0]||'A')}</div><div><b>${esc(x.name)}</b><span>${esc(x.cat||'—')} · v${esc(x.version||'Latest')} ${x.featured?'· Featured':''}</span><small>${esc(x.source||x.type||'—')} · ${(x.versions||[]).length} versions</small></div></div><div class="admin-item-actions"><button class="mini-btn edit-btn" data-id="${esc(x.id)}">Edit</button><button class="mini-delete remove-btn" data-id="${esc(x.id)}">Delete</button></div></div>`).join(''):'<div class="empty"><b>No apps found</b><span>Add an app or change your search.</span></div>';
}
function collect(){const name=$('#fName').value.trim(),id=$('#fId').value.trim().toLowerCase().replace(/\s+/g,'-');return {id,name,cat:$('#fCat').value,tag:$('#fTag').value.trim(),desc:$('#fDesc').value.trim(),version:$('#fVersion').value.trim()||'Latest',size:$('#fSize').value.trim()||'—',platform:$('#fPlatform').value.trim()||'Multiple platforms',link:$('#fLink').value.trim(),download:$('#fDownload').value.trim()||$('#fLink').value.trim(),source:$('#fType').selectedOptions[0].textContent,type:$('#fType').value,initial:$('#fInitial').value.trim()||name[0]||'A',color:$('#fColor').value.trim()||'#315efb',featured:$('#fFeatured').checked,updated:new Date().toISOString().slice(0,10),versions:collectVersions(),community:$('#fType').value==='community'} }
function downloadJSON(){const blob=new Blob([JSON.stringify(load(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='openshelf-apps.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function setupTheme(){const b=$('#themeBtn');if(!b)return;let dark=localStorage.getItem('openshelf_theme')==='dark';const apply=()=>{document.documentElement.classList.toggle('dark-mode',dark);document.body.classList.toggle('dark',dark);b.textContent=dark?'☀':'☾'};apply();b.onclick=()=>{dark=!dark;localStorage.setItem('openshelf_theme',dark?'dark':'light');apply()}}
function showApp(){ $('#loginGate').hidden=true;$('#adminApp').hidden=false;setupTheme();render();resetForm() }
function init(){
if(sessionStorage.getItem(SESSION)==='1')showApp();
$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#adminPin').value==='1234'){sessionStorage.setItem(SESSION,'1');showApp()}else{alert('Incorrect PIN. Demo PIN: 1234');$('#adminPin').select()}};
$('#logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION);location.reload()};
$('#resetBtn').onclick=resetForm; $('#addVersionBtn').onclick=()=>addVersionRow(); $('#adminSearch').oninput=render;
$('#exportBtn').onclick=downloadJSON; $('#importBtn').onclick=()=>$('#importFile').click();
$('#importFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data))throw Error();save(data);render();alert('Catalog imported successfully.')}catch{alert('Invalid JSON catalog.')}};r.readAsText(file);e.target.value=''};
$('#appForm').onsubmit=e=>{e.preventDefault();const item=collect();if(!item.id||!item.name)return;let a=load();const idx=a.findIndex(x=>x.id===item.id);if(idx>=0)a[idx]={...a[idx],...item};else a.unshift(item);save(a);render();edit(a.find(x=>x.id===item.id));alert(idx>=0?'App updated successfully.':'App published to this browser catalog.');};
$('#deleteBtn').onclick=()=>{if(!editing)return;if(confirm('Delete this app from the browser catalog?')){save(load().filter(x=>x.id!==editing));resetForm();render()}};
$('#adminList').onclick=e=>{const editBtn=e.target.closest('.edit-btn'),del=e.target.closest('.remove-btn');if(editBtn){const a=load().find(x=>x.id===editBtn.dataset.id);if(a)edit(a)}if(del&&confirm('Delete this app?')){save(load().filter(x=>x.id!==del.dataset.id));if(editing===del.dataset.id)resetForm();render()}};
}
document.addEventListener('DOMContentLoaded',init);
})();
