(() => {
  const $ = s => document.querySelector(s);
  const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const KEY='openshelf_apps_v34', SESSION='openshelf_admin_session_v34', CFG='openshelf_supabase_cfg_v34';
  let editing=null, supabase=null;
  const clone = a => JSON.parse(JSON.stringify(a));
  const loadLocal=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:(window.APPS||[]).map(clone)}catch{return (window.APPS||[]).map(clone)}};
  const saveLocal=a=>localStorage.setItem(KEY,JSON.stringify(a));
  const getCfg=()=>{try{return JSON.parse(localStorage.getItem(CFG)||'null')}catch{return null}};
  const setCfg=c=>localStorage.setItem(CFG,JSON.stringify(c));
  function initSupabase(){const c=getCfg(); if(!c?.url||!c?.key||!window.supabase)return null; try{supabase=window.supabase.createClient(c.url,c.key);return supabase}catch{return null}}
  function applyTheme(){const dark=localStorage.getItem('openshelf_theme')==='dark';document.documentElement.classList.toggle('dark-mode',dark);document.body.classList.toggle('dark',dark);$('#themeBtn').textContent=dark?'☀':'☾'}
  function versionsOf(a){return Array.isArray(a.versions)?a.versions:[]}
  function addVersionRow(v={version:'',url:'',label:'Previous release'}){const r=document.createElement('div');r.className='version-row';r.innerHTML=`<input class="v-version" placeholder="Version" value="${esc(v.version)}"><input class="v-url" type="url" placeholder="Download URL" value="${esc(v.url)}"><input class="v-label" placeholder="Label" value="${esc(v.label||'Previous release')}"><button class="btn ghost" type="button">×</button>`;r.querySelector('button').onclick=()=>r.remove();$('#versionRows').appendChild(r)}
  function collectVersions(){return [...document.querySelectorAll('.version-row')].map(r=>({version:r.querySelector('.v-version').value.trim(),url:r.querySelector('.v-url').value.trim(),label:r.querySelector('.v-label').value.trim()||'Previous release'})).filter(v=>v.version)}
  function resetForm(){editing=null;$('#appForm').reset();$('#fColor').value='#315efb';$('#versionRows').innerHTML='';$('#editorTitle').textContent='Add new app';$('#saveBtn').textContent='Publish app →';$('#deleteBtn').disabled=true;$('#apkFile').value='';$('#fileMeta').textContent='Choose an app file from your phone. Max size depends on your storage provider.';$('#uploadProgress').style.width='0';$('#saveStatus').textContent=''}
  function edit(a){editing=a.id;['Name','Id','Cat','Tag','Desc','Version','Size','Platform','Type','Link','Download','Initial','Color'].forEach(x=>{});$('#fName').value=a.name||'';$('#fId').value=a.id||'';$('#fCat').value=a.cat||'utility';$('#fTag').value=a.tag||'';$('#fDesc').value=a.desc||'';$('#fVersion').value=a.version||'';$('#fSize').value=a.size||'';$('#fPlatform').value=a.platform||'';$('#fType').value=a.type||'official';$('#fLink').value=a.link||'';$('#fDownload').value=a.download||'';$('#fInitial').value=a.initial||'';$('#fColor').value=a.color||'#315efb';$('#fFeatured').checked=!!a.featured;$('#versionRows').innerHTML='';versionsOf(a).forEach(addVersionRow);$('#editorTitle').textContent='Edit '+a.name;$('#saveBtn').textContent='Save changes →';$('#deleteBtn').disabled=false;window.scrollTo({top:0,behavior:'smooth'})}
  function collect(){const name=$('#fName').value.trim(),id=$('#fId').value.trim().toLowerCase().replace(/\s+/g,'-');return {id,name,cat:$('#fCat').value,tag:$('#fTag').value.trim(),desc:$('#fDesc').value.trim(),version:$('#fVersion').value.trim()||'Latest',size:$('#fSize').value.trim()||'—',platform:$('#fPlatform').value.trim()||'Multiple platforms',link:$('#fLink').value.trim(),download:$('#fDownload').value.trim(),source:$('#fType').selectedOptions[0].textContent,type:$('#fType').value,initial:$('#fInitial').value.trim()||name[0]||'A',color:$('#fColor').value.trim()||'#315efb',featured:$('#fFeatured').checked,updated:new Date().toISOString().slice(0,10),versions:collectVersions(),community:$('#fType').value==='community'}}
  function render(list=loadLocal()){const q=($('#adminSearch').value||'').toLowerCase();const a=list.filter(x=>[x.name,x.id,x.cat,x.tag].join(' ').toLowerCase().includes(q));$('#statApps').textContent=list.length;$('#statFeatured').textContent=list.filter(x=>x.featured).length;$('#statCats').textContent=new Set(list.map(x=>x.cat).filter(Boolean)).size;$('#statVersions').textContent=list.reduce((n,x)=>n+(x.versions?.length||0),0);$('#adminList').innerHTML=a.length?a.map(x=>`<div class="app-row"><div class="app-main"><div class="mini-icon" style="background:${esc(x.color||'#315efb')}">${esc(x.initial||x.name?.[0]||'A')}</div><div><b>${esc(x.name)}</b><div class="muted">${esc(x.cat||'—')} · v${esc(x.version||'Latest')}</div></div></div><div><button class="btn ghost edit-btn" data-id="${esc(x.id)}">Edit</button></div></div>`).join(''):'<p class="muted">No apps found.</p>'}
  async function uploadFile(file){if(!file)return null; const cfg=getCfg(); if(!supabase||!cfg)return null; const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`apps/${Date.now()}-${safe}`;$('#fileMeta').textContent=`Uploading ${file.name}...`;$('#uploadProgress').style.width='35%';const {error}=await supabase.storage.from(cfg.bucket||'app-files').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(error)throw error;$('#uploadProgress').style.width='80%';const {data}=supabase.storage.from(cfg.bucket||'app-files').getPublicUrl(path);$('#uploadProgress').style.width='100%';$('#fileMeta').textContent=`Uploaded: ${file.name}`;return data.publicUrl}
  async function saveRemote(item){if(!supabase)return false;const payload={...item,updated:new Date().toISOString().slice(0,10)};const {error}=await supabase.from('apps').upsert(payload,{onConflict:'id'});if(error)throw error;return true}
  function openConfig(){const c=getCfg()||{};$('#sbUrl').value=c.url||'';$('#sbKey').value=c.key||'';$('#sbBucket').value=c.bucket||'app-files';$('#configStatus').textContent=''}
  async function init(){applyTheme();initSupabase();$('#pinLogin').onclick=()=>{if($('#adminPin').value==='1234'){sessionStorage.setItem(SESSION,'1');show()}else alert('Incorrect PIN. Demo PIN: 1234')};$('#logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION);location.reload()};$('#themeBtn').onclick=()=>{localStorage.setItem('openshelf_theme',localStorage.getItem('openshelf_theme')==='dark'?'light':'dark');applyTheme()};$('#configBtn').onclick=()=>{$('#configModal').classList.remove('hidden');openConfig()};$('#closeConfig').onclick=()=>$('#configModal').classList.add('hidden');$('#saveConfig').onclick=()=>{const c={url:$('#sbUrl').value.trim(),key:$('#sbKey').value.trim(),bucket:$('#sbBucket').value.trim()||'app-files'};setCfg(c);if(initSupabase()){$('#configStatus').textContent='Supabase connected. Make sure your bucket and database policies are configured.'}else $('#configStatus').textContent='Could not initialize Supabase. Check the URL/key.'};$('#resetBtn').onclick=resetForm;$('#addVersionBtn').onclick=()=>addVersionRow();$('#adminSearch').oninput=()=>render();$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(loadLocal(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='openshelf-apps.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
  $('#apkFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;$('#fileMeta').textContent=`Selected: ${f.name} (${(f.size/1024/1024).toFixed(1)} MB)`;if(supabase){try{const url=await uploadFile(f);if(url)$('#fDownload').value=url}catch(err){$('#saveStatus').textContent='Upload failed: '+(err.message||err);$('#uploadProgress').style.width='0'}}else{$('#saveStatus').textContent='File selected. Connect Supabase to make it publicly downloadable.'}};
  $('#appForm').onsubmit=async e=>{e.preventDefault();const item=collect();const f=$('#apkFile').files[0];$('#saveBtn').disabled=true;try{if(f&&supabase){const url=await uploadFile(f);if(url)item.download=url}let a=loadLocal();const i=a.findIndex(x=>x.id===item.id);if(i>=0)a[i]={...a[i],...item};else a.unshift(item);saveLocal(a);if(supabase){await saveRemote(item);$('#saveStatus').textContent='Published to Supabase + local backup. The public site still needs to read the Supabase table to display remote apps.'}else $('#saveStatus').textContent='Saved to this browser only. Connect Supabase for public upload.';render(a);edit(item)}catch(err){$('#saveStatus').textContent='Could not publish: '+(err.message||err)}finally{$('#saveBtn').disabled=false}};
  $('#deleteBtn').onclick=()=>{if(!editing)return;if(confirm('Delete this app from the local catalog?')){saveLocal(loadLocal().filter(x=>x.id!==editing));resetForm();render()}};$('#adminList').onclick=e=>{const b=e.target.closest('.edit-btn');if(b){const a=loadLocal().find(x=>x.id===b.dataset.id);if(a)edit(a)}};
  if(sessionStorage.getItem(SESSION)==='1')show();else $('#loginGate').classList.remove('hidden');
  }
  function show(){$('#loginGate').classList.add('hidden');$('#adminApp').classList.remove('hidden');render();resetForm();}
  document.addEventListener('DOMContentLoaded',init);
})();
