const APPS=[
{id:'libreoffice',name:'LibreOffice',cat:'productivity',tag:'Office Suite',desc:'Full office suite for documents, spreadsheets and presentations. Free and open-source.',size:'300 MB',initial:'L',color:'#15803d',link:'https://www.libreoffice.org/download/download/',source:'Official website',open:true,platform:'Windows · macOS · Linux',featured:true},
{id:'gimp',name:'GIMP',cat:'media',tag:'Photo Editor',desc:'Powerful image editor for photo retouching, graphic design and digital art.',size:'280 MB',initial:'G',color:'#a16207',link:'https://www.gimp.org/downloads/',source:'Official website',open:true,platform:'Windows · macOS · Linux',featured:true},
{id:'vlc',name:'VLC Media Player',cat:'media',tag:'Video Player',desc:'Plays almost any video or audio format with no ads or tracking.',size:'40 MB',initial:'V',color:'#b45309',link:'https://www.videolan.org/vlc/',source:'Official website',open:true,platform:'Windows · macOS · Linux · Android · iOS',featured:true},
{id:'obs',name:'OBS Studio',cat:'media',tag:'Screen Recorder',desc:'Professional free software for recording, streaming and live production.',size:'120 MB',initial:'O',color:'#334155',link:'https://obsproject.com/download',source:'Official website',open:true,platform:'Windows · macOS · Linux',featured:true},
{id:'notion',name:'Notion',cat:'productivity',tag:'Notes & Docs',desc:'Notes, documents and task management with a free personal plan.',size:'Web / App',initial:'N',color:'#111827',link:'https://www.notion.so/desktop',source:'Official website',open:false,platform:'Windows · macOS · Android · iOS'},
{id:'7zip',name:'7-Zip',cat:'utility',tag:'File Archiver',desc:'Fast open-source compression and extraction tool supporting many archive formats.',size:'1.5 MB',initial:'7',color:'#7c3aed',link:'https://www.7-zip.org/',source:'Official website',open:true,platform:'Windows',featured:true},
{id:'vscode',name:'Visual Studio Code',cat:'dev',tag:'Code Editor',desc:'Extensible code editor with debugging, Git integration and thousands of extensions.',size:'90 MB',initial:'<>',color:'#0284c7',link:'https://code.visualstudio.com/download',source:'Official website',open:false,platform:'Windows · macOS · Linux',featured:true},
{id:'audacity',name:'Audacity',cat:'media',tag:'Audio Editor',desc:'Free open-source audio recording and editing software.',size:'40 MB',initial:'A',color:'#ca8a04',link:'https://www.audacityteam.org/download/',source:'Official website',open:true,platform:'Windows · macOS · Linux'},
{id:'capcut',name:'CapCut',cat:'media',tag:'Video Editor',desc:'Easy-to-use video editor for short-form content and everyday editing.',size:'200 MB',initial:'C',color:'#111827',link:'https://www.capcut.com/',source:'Official website',open:false,platform:'Windows · macOS · Android · iOS'},
{id:'wps-office',name:'WPS Office',cat:'office',tag:'Office Suite',desc:'Office productivity app. Existing OpenShelf listing retained as a community download.',size:'APK',initial:'W',color:'#16a34a',link:'https://github.com/openshelf-talha/openshelf.github.io/releases/download/V1.0/WPS_Office_26.10.5_1779522294_latestmodapks.com.apk',source:'OpenShelf community release',open:false,platform:'Android',community:true}
];
const CATS=[['all','All Apps'],['productivity','Productivity'],['media','Media'],['utility','Utilities'],['dev','Developer'],['office','Office']];
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function card(a){return `<article class="app-card"><a href="app.html?id=${a.id}"><div class="app-head"><div class="app-icon" style="background:${a.color}">${esc(a.initial)}</div><div><div class="app-name">${esc(a.name)}</div><div class="app-tag">${esc(a.tag)}</div></div></div></a><p class="desc">${esc(a.desc)}</p><div class="badges"><span class="badge green">${a.open?'OPEN SOURCE':'FREE PLAN'}</span><span class="badge blue">${esc(a.platform.split(' · ')[0])}</span>${a.community?'<span class="badge">COMMUNITY</span>':''}</div><div class="card-foot"><span class="size">${esc(a.size)}</span><a class="get" href="${a.link}" target="_blank" rel="noopener">Get app ↗</a></div></article>`}
function renderCards(list,el){el.innerHTML=list.length?list.map(card).join(''):'<div class="empty" style="grid-column:1/-1">No apps found. Try another search or category.</div>'}
function setupHome(){const grid=document.querySelector('#appGrid');if(!grid)return;let cat='all',q='';const input=document.querySelector('#searchInput');const sort=document.querySelector('#sort');function run(){let list=APPS.filter(a=>(cat==='all'||a.cat===cat)&&(`${a.name} ${a.tag} ${a.desc}`.toLowerCase().includes(q)));if(sort?.value==='az')list.sort((a,b)=>a.name.localeCompare(b.name));if(sort?.value==='za')list.sort((a,b)=>b.name.localeCompare(a.name));if(sort?.value==='featured')list.sort((a,b)=>Number(b.featured)-Number(a.featured));renderCards(list,grid);const count=document.querySelector('#resultCount');if(count)count.textContent=`${list.length} apps`;}
input?.addEventListener('input',e=>{q=e.target.value.toLowerCase().trim();run()});sort?.addEventListener('change',run);document.querySelectorAll('.chip').forEach(x=>x.addEventListener('click',()=>{document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));x.classList.add('active');cat=x.dataset.cat;run()}));run();const fg=document.querySelector('#featuredGrid');if(fg)renderCards(APPS.filter(a=>a.featured).slice(0,4),fg);}
function setupDetail(){const box=document.querySelector('#detail');if(!box)return;const id=new URLSearchParams(location.search).get('id');const a=APPS.find(x=>x.id===id)||APPS[0];document.title=`${a.name} — OpenShelf`;box.innerHTML=`<div class="detail-card"><div class="detail-top"><div class="app-icon" style="background:${a.color}">${esc(a.initial)}</div><div><h1>${esc(a.name)}</h1><div class="detail-meta">${esc(a.tag)} · ${esc(a.platform)} · ${esc(a.size)}</div></div></div><div class="detail-actions"><a class="btn primary" href="${a.link}" target="_blank" rel="noopener">Download / Visit ↗</a><a class="btn" href="index.html">← Back to apps</a></div>${a.community?'<div class="notice"><strong>Community download:</strong> This listing uses an OpenShelf-hosted/community release rather than an official vendor download. Review the source before installing.</div>':''}<div style="margin-top:26px"><h2>About ${esc(a.name)}</h2><p style="color:var(--muted);line-height:1.8">${esc(a.desc)}</p><div class="trust" style="margin-top:20px"><div class="trust-item"><b>Source</b><span>${esc(a.source)}</span></div><div class="trust-item"><b>License / access</b><span>${a.open?'Open-source':'Free or free-plan availability'}</span></div><div class="trust-item"><b>Platforms</b><span>${esc(a.platform)}</span></div></div></div></div>`}
document.addEventListener('DOMContentLoaded',()=>{setupHome();setupDetail();});
