const APPS=[
{id:'libreoffice',name:'LibreOffice',cat:'productivity',tag:'Office Suite',desc:'A full office suite for documents, spreadsheets and presentations.',version:'26.2',size:'300 MB',initial:'L',color:'#0f8a4b',link:'https://www.libreoffice.org/download/download/',download:'https://www.libreoffice.org/download/download/',source:'Official',type:'open',platform:'Windows · macOS · Linux',featured:true,updated:'2026-08-14',versions:['26.2','25.8','25.2']},
{id:'gimp',name:'GIMP',cat:'media',tag:'Photo Editor',desc:'Powerful image editor for photo retouching, graphic design and digital art.',version:'3.0',size:'280 MB',initial:'G',color:'#8b5e12',link:'https://www.gimp.org/downloads/',download:'https://www.gimp.org/downloads/',source:'Official',type:'open',platform:'Windows · macOS · Linux',featured:true,updated:'2026-08-13',versions:['3.0','2.10.38']},
{id:'vlc',name:'VLC Media Player',cat:'media',tag:'Video Player',desc:'A versatile media player that handles almost any video or audio format.',version:'3.0.21',size:'40 MB',initial:'V',color:'#b36a00',link:'https://www.videolan.org/vlc/',download:'https://www.videolan.org/vlc/',source:'Official',type:'open',platform:'Windows · macOS · Linux · Android · iOS',featured:true,updated:'2026-08-12',versions:['3.0.21','3.0.20','3.0.19']},
{id:'obs',name:'OBS Studio',cat:'media',tag:'Screen Recorder',desc:'Professional free software for recording, streaming and live production.',version:'32.0',size:'120 MB',initial:'O',color:'#334155',link:'https://obsproject.com/download',download:'https://obsproject.com/download',source:'Official',type:'open',platform:'Windows · macOS · Linux',featured:true,updated:'2026-08-10',versions:['32.0','31.0','30.2']},
{id:'7zip',name:'7-Zip',cat:'utility',tag:'File Archiver',desc:'Fast open-source compression and extraction tool for many archive formats.',version:'26.00',size:'1.5 MB',initial:'7',color:'#6941c6',link:'https://www.7-zip.org/',download:'https://www.7-zip.org/',source:'Official',type:'open',platform:'Windows',featured:true,updated:'2026-08-09',versions:['26.00','25.01','24.09']},
{id:'vscode',name:'Visual Studio Code',cat:'dev',tag:'Code Editor',desc:'Extensible code editor with debugging, Git integration and thousands of extensions.',version:'1.104',size:'90 MB',initial:'<>',color:'#087bb5',link:'https://code.visualstudio.com/download',download:'https://code.visualstudio.com/download',source:'Official',type:'free',platform:'Windows · macOS · Linux',featured:true,updated:'2026-08-08',versions:['1.104','1.103','1.102']},
{id:'audacity',name:'Audacity',cat:'media',tag:'Audio Editor',desc:'Free open-source audio recording and editing software.',version:'3.7',size:'40 MB',initial:'A',color:'#b98600',link:'https://www.audacityteam.org/download/',download:'https://www.audacityteam.org/download/',source:'Official',type:'open',platform:'Windows · macOS · Linux',updated:'2026-08-06',versions:['3.7','3.6','3.5']},
{id:'notion',name:'Notion',cat:'productivity',tag:'Notes & Docs',desc:'Notes, documents, wikis and task management with a free personal plan.',version:'Latest',size:'Web / App',initial:'N',color:'#111827',link:'https://www.notion.so/desktop',download:'https://www.notion.so/desktop',source:'Official',type:'free',platform:'Windows · macOS · Android · iOS',updated:'2026-08-04'},
{id:'capcut',name:'CapCut',cat:'media',tag:'Video Editor',desc:'Easy-to-use video editor for short-form content and everyday editing.',version:'Latest',size:'200 MB',initial:'C',color:'#111827',link:'https://www.capcut.com/',download:'https://www.capcut.com/',source:'Official',type:'free',platform:'Windows · macOS · Android · iOS',updated:'2026-08-02'},
{id:'wps-office',name:'WPS Office',cat:'office',tag:'Office Suite',desc:'Office productivity app with an OpenShelf community release listing.',version:'26.10.5',size:'APK',initial:'W',color:'#13a65a',link:'https://www.wps.com/',download:'https://github.com/openshelf-talha/openshelf.github.io/releases/download/V1.0/WPS_Office_26.10.5_1779522294_latestmodapks.com.apk',source:'Community',type:'community',platform:'Android',updated:'2026-08-01',versions:['26.10.5'],community:true}
];
const CATEGORIES=[
{id:'all',name:'All apps',icon:'✦',desc:'Everything in the library'},
{id:'productivity',name:'Productivity',icon:'✓',desc:'Work, notes & organization'},
{id:'media',name:'Media',icon:'▶',desc:'Video, audio & creative tools'},
{id:'utility',name:'Utilities',icon:'⚙',desc:'Useful everyday tools'},
{id:'dev',name:'Developer',icon:'</>',desc:'Build, code & ship'},
{id:'office',name:'Office',icon:'▤',desc:'Documents & business'},
{id:'communication',name:'Communication',icon:'◉',desc:'Chat, calls & communities'},
{id:'games',name:'Games',icon:'◆',desc:'Play & entertainment'}
];